config/routes.rb
Golfalytics::Application.routes.draw do

  root to: 'static_pages#home'

  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users
  resources :sessions
  resources :activities

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password

  has_many :activities, dependent: :destroy

  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, success: "Welcome!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.haml
%h1 Sign up

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :email 
    = f.email_field :email
  .field
    = f.label :password 
    = f.password_field :password
  .actions
    = f.submit "Sign Up"

app/views/users/show.html.haml
%h1 Home

%p= link_to "Enter a new activity", new_activity_path

%ul
  - @user.activities.each do |activity|
    %li
      - facility = Facility.find(activity.facility_id)
      - venue = Venue.find(facility.venue_id)
      - if activity.activity_type == 'Play'
        = "Played at"
      - elsif activity.activity_type == 'Practice'
        = "Practiced at"
      = "#{venue.name} #{':' if !facility.name.blank?} #{facility.name if !facility.name.blank?} on #{activity.date_completed}"